### ISSUE TITLE
Doens't work for me

### ISSUE THREAD

**Issue by major-mayer** [FrancescoCaracciolo/OSK-Touchpad-inverse-toggle-Gnome-Ext#1]
I am using a Yoga C940 convertible notebook and at least for me, this extension has simply no effect.
Neither when i manually disable the touchpad via the keyboard or when i fold the notebook and the touchpad gets disabled automatically.
Have you tested this extension with Gnome 43?
Anything that I can provide you to debug this issue?

**Comment by FrancescoCaracciolo** [comment]
Hello, I tested this extension on Gnome 43, and should work (at the moment, I'm testing on a Lenovo Ideapad Flex 5 with Fedora 37).
To help me find the issue, this information should help me:
1) Is the extension enabled? (sorry fo the stupid question but you never know)
2) When you flip your notebook, is the "touchapd disabled/enabled" icon shown?
3)  In Settings, "Mouse and touchpad", Enabling/Disabling Touchpad setting changes something with the OSK on accessibility settings?
![image](https://user-images.githubusercontent.com/67018178/216660678-ced0cf66-e0ce-4250-89f9-960edeffd33b.png)

**Comment by major-mayer** [comment]
Hi, thanks for you fast help.
1. Yes the extension is enabled ;)
2. When i flip the notebook, this icon is not shown. It's only shown when I disable the touchpad with the special/function key on the keyboard.
3. Yes when i change this value in the settings, the OSK is indeed also enabled/ disabled in the accessibility settings. This is very weird, because when I disable the touchpad via the function key, this is not the case.

**Comment by FrancescoCaracciolo** [comment]
I think that on your laptop touchpad is disabled hardware side. On mine, when I flip my notebook, it is disabled software side (that toggle changes), that's why this extension exists. 
It looks like on yours things are pretty different. 
However, if you want, you can add custom keyboard shortcuts with gnome settings to enable/disable touchpad software side.
To do this, go to settings -> keyboard -> customize shortcuts -> add custom shortcut
And map these two commands to whatever you like:
```
gsettings set org.gnome.desktop.peripherals.touchpad send-events enabled
```
Enables touchpad
```
gsettings set org.gnome.desktop.peripherals.touchpad send-events disabled
```
Disables touchpad.
Techincally you can also create a command to just toggle it with a bash script.
Thanks for reporting this to me, hope that this helped you.

**Comment by major-mayer** [comment]
Yeah I also thought of something similiar. Indeed, it's likely that my touchpad/ keyboard is disabled on hardware-level.
The custom keyboard shortcut is a nice idea, but then i can also just go and enable the on-screen keyboard via the accessibility menu in the menu bar (on the top with those small icons).

I am still wondering tho, why your extension doesn't  work when I manually disable the touchpad via the function key.
At least in this case, something must be notices on software-level, because otherwise this icon wouldn't pop up.

**Comment by FrancescoCaracciolo** [comment]
My extension just watches for that touchpad toggle and changes osk value accordingly. If you can detect another setting that is changed in your case I can also watch for that.

**Comment by major-mayer** [comment]
I found out that I needed an additional kernel module (https://github.com/lukas-w/yoga-usage-mode) to correctly communicate the "tablet-mode" to the desktop environment.
With this enabled, I don't need an additional extension anymore, because the OSK appears automatically when in tablet mode.
So I will close this issue. Thank you anyway :)
